name: Sync LeetCode

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # runs daily

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Sync LeetCode
        uses: joshcai/leetcode-sync@master
        with:
          leetcode_session: ${{ secrets.LEETCODE_SESSION }}
          csrf_token: ${{ secrets.CSRF_TOKEN }}
