name: Sync LeetCode

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: LeetCode Sync
        uses: ashishgpt/leetcode-sync-action@v1.0.1
        with:
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          csrf-token: ${{ secrets.CSRF_TOKEN }}
